version: 2.1

orbs:
  slack: circleci/slack@5.0

parameters:
  publish_sdk:
    type: boolean
    default: false
  environment:
    default: "test"
    type: enum
    enum: [ "test","staging","production" ]

executors:
  python-executor:
    docker:
      - image: cimg/python:3.13

jobs:
  integration-tests:
    working_directory: /home/circleci/project/
    executor: python-executor
    circleci_ip_ranges: true
    environment:
      ENVIRONMENT: << pipeline.parameters.environment >>
    steps:
      - checkout
      - run:
          name: Install SDK and dependencies and Run PyTest
          command: |
            python3 -m venv myapp
            source myapp/bin/activate 
            pip install --upgrade pip
            pip install 'hibachi-xyz[dev]'
            ENVIRONMENT=$ENVIRONMENT pytest python-sdk/ -k "not example"
      - slack/notify:
          event: fail
          channel: python-sdk-tests
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "SDK Integration Tests Failed",
                      "emoji": true
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Pipeline URL:* <$CIRCLE_BUILD_URL|View on CircleCI>"
                    }
                  ]
                }
              ]
            }

  deploy-to-pypi:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Patch version dynamically
          command: |
            VERSION_SUFFIX=$(date +%Y%m%d%H%M%S)
            # sed -i "s/^version = .*/version = \"0.0.1.dev$VERSION_SUFFIX\"/" python-sdk/pyproject.toml
            sed -i "s/^version = .*/version = \"0.1.10\"/" python-sdk/pyproject.toml
            grep version python-sdk/pyproject.toml
      - run: pip install build twine
      - run:
          name: Build SDK
          command: |
            echo 'dry run publish'
            # python -m build -s -w python-sdk
      - run:
          name: Publish to PyPI
          command: |
            # twine upload python-sdk/dist/* -u __token__ -p "$PYPI_TOKEN"
            echo 'dry run publish'

workflows:
  sdk-tests-and-deploy:
    jobs:
      # - integration-tests:
      #     context:
      #       - slack-secrets
      - deploy-to-pypi:
          # requires:
          #   - integration-tests
          filters:
            branches:
              only:
                - release


  
